name: .NET

on:
  push:
    tags:
      - '1.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        #dotnet publish -r win-x64 -c Release --no-self-contained
        dotnet publish -f net6.0 -c Release --no-self-contained
        (cd ./TestApp1/bin/Release/net6.0/publish && zip -r - .) >app-${{ env.RELEASE_VERSION }}.zip

    # ARTIFACTS
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ env.RELEASE_VERSION }}
        path: | 
          app-${{ env.RELEASE_VERSION }}.zip

    # RELEASE
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: release-${{ env.RELEASE_VERSION }}
        files: |
          app-${{ env.RELEASE_VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}